import { motion } from 'framer-motion';
import { Settings2 } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { DEFAULT_RULES } from '@/lib/engine';

const ruleEffectiveness = DEFAULT_RULES.map(r => ({
  name: r.name,
  triggers: r.triggerCount,
  savings: Math.round(r.triggerCount * (r.category === 'guilt-tax' ? 50 : r.category === 'overspend' ? 100 : 8)),
}));

export default function AdminRules() {
  return (
    <div className="max-w-5xl space-y-6">
      <h1 className="text-2xl font-bold font-heading text-foreground flex items-center gap-2">
        <Settings2 className="w-6 h-6 text-primary" /> Rule Analytics
      </h1>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: 'Active Rules', value: DEFAULT_RULES.filter(r => r.enabled).length },
          { label: 'Total Triggers', value: DEFAULT_RULES.reduce((s, r) => s + r.triggerCount, 0) },
          { label: 'Avg Triggers/Rule', value: Math.round(DEFAULT_RULES.reduce((s, r) => s + r.triggerCount, 0) / DEFAULT_RULES.length) },
          { label: 'Most Effective', value: 'Round-Up' },
        ].map((s, i) => (
          <div key={i} className="kpi-card text-center">
            <p className="text-2xl font-bold font-heading text-foreground">{s.value}</p>
            <p className="text-xs text-muted-foreground mt-1">{s.label}</p>
          </div>
        ))}
      </div>

      <div className="glass-card p-5">
        <h3 className="text-base font-semibold font-heading text-foreground mb-4">Rule Trigger Frequency</h3>
        <div className="h-64">
          <ResponsiveContainer>
            <BarChart data={ruleEffectiveness}>
              <XAxis dataKey="name" tick={{ fontSize: 11 }} />
              <YAxis />
              <Tooltip />
              <Bar dataKey="triggers" fill="hsl(174 62% 40%)" radius={[6, 6, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="glass-card p-5">
        <h3 className="text-base font-semibold font-heading text-foreground mb-4">Savings Generated by Rule</h3>
        <div className="h-64">
          <ResponsiveContainer>
            <BarChart data={ruleEffectiveness}>
              <XAxis dataKey="name" tick={{ fontSize: 11 }} />
              <YAxis tickFormatter={v => `₹${v}`} />
              <Tooltip formatter={(v: number) => `₹${v}`} />
              <Bar dataKey="savings" fill="hsl(152 60% 42%)" radius={[6, 6, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
}
